const index = () => {
    return (
        <>
            <section className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                {[
                    ["Users", "1.2k", "People"],
                    ["Sales", "$24.3k", "Revenue"],
                    ["Reports", "84", "Open"]
                ].map((c, i) => (<div key={i} className="bg-white p-4 rounded-lg shadow-sm border flex flex-col">
                    <div className="text-sm text-slate-500">{c[2]}</div>
                    <div className="mt-2 text-xl font-bold">{c[1]}</div>
                    <div className="text-xs text-slate-400 mt-1">{c[0]}</div>
                </div>))}
            </section>

            <section className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                <div className="lg:col-span-2 bg-white p-4 rounded-lg shadow-sm border">
                    <h3 className="font-medium mb-3">Recent Activity</h3>
                    <ul className="space-y-3">
                        {["User John placed an order", "New signup: lisa@example.com", "Report generated by analytics"].map((t, i) => (<li key={i} className="text-sm text-slate-600">{t}</li>))}
                    </ul>
                </div>
                <div className="bg-white p-4 rounded-lg shadow-sm border">
                    <h3 className="font-medium mb-3">Quick Actions</h3>
                    <div className="flex flex-col gap-2">
                        <button className="py-2 px-3 border rounded">Manage Users</button>
                        <button className="py-2 px-3 border rounded">Export</button>
                        <button className="py-2 px-3 border rounded">Settings</button>
                    </div>
                </div>
            </section>
        </>
    )
}

export default index